In [ ]:
import numpy as np

n = int(input("Ingrese el numero de matrices a trabajar: "))
A = np.random.rand(n,n)
B = np.random.rand(n,)

alpha = 3 * n
ADD = np.dot(A,A.T) + alpha*np.identity(n)
A = ADD

In [4]:
print(A)
print("")
print(B)

[[13.71481624  1.04172903  1.47234584  0.75227708]
 [ 1.04172903 12.69974321  0.92203088  0.3817862 ]
 [ 1.47234584  0.92203088 13.49328647  0.67356783]
 [ 0.75227708  0.3817862   0.67356783 12.44660835]]

[0.91167139 0.33246493 0.92928579 0.09785158]


In [ ]:
n = len(B)
count = 0

for i in range(n):
    Aii = A[i][i]
    suma = 0

    for j in range(n):
        if i